title: Hacky
description: >-
  A completely free education application.
permalink: /:title/

author: Jinx

# Hackable variables

## AppKit variables
useAppKit: no

siteRoot: /
circularHome: no

coursesSliderOnHome: yes
guidesOnHome: yes

guidesOnHomeLimit: 5

coursePageShowAbout: yes
coursePageAboutShowYoulearn: yes
coursePageAboutShowRequirements: yes
coursePageAboutShowDuration: yes
coursePageAboutShowDifficulty: yes

coursePageCurriculumTitle: "Curriculum"

## LearnUP variables
useLearnUp: yes
